export enum EVENTS {
    HELLO = "HELLO",
    RESPONSE = "RESPONSE",
    UPDATE = "UPDATE",
    FIRST_CONNECT = "FIRST_CONNECT",
    REMOVE_PLAYER = "REMOVE_PLAYER",
    SEND = "SEND",
    NEW_MESSAGE = "NEW_MESSAGE",
}